# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            HALIL AYYILDIZ
tagline:          Technical Blog
description:      Software Developer
url:              blog.halilayyildiz.com/
baseurl:          /

author:
  name:           Halil Ayyildiz
  url:            http://www.halilayyildiz.com

paginate:         5

link:
  twitter:        https://twitter.com/halilayyildiz
  github:         https://github.com/halilayyildiz
  linkedin:       https://www.linkedin.com/in/halilayyildiz/
  
  