# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Halil Ayyildiz
tagline:          'Technical Blog'
description:      >- 
                  My thoughts and experiences on software development topics
                  <a href="http://twitter.com/halilayyildiz" target="_blank">@halilayyildiz</a>
url:              blog.halilayyildiz.com/
baseurl:          /

author:
  name:           'Halil Ayyildiz'
  url:            http://www.halilayyildiz.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/halilayyildiz/
  